imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# doctrine migrations configuration
doctrine_migrations:
    dir_name: "%kernel.root_dir%/db/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

# Swiftmailer configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# easy admin configuration
easy_admin:
    site_name: 'Drullan Test'
    design:
        color_scheme: 'light'
        form_theme: 'vertical'
        menu: 
            - { entity: 'Reviews', icon: 'play' }
            - label: 'Criteria'
              icon: 'heartbeat'
              children: 
                - { entity: 'Topics', icon: 'quote-right' }
                - { entity: 'Scores', icon: 'heart' }

    entities:
        Reviews:
            class: AppBundle\Entity\Reviews
            label: 'Reviews'
            list:
                title: "Most recent Reviews..."
                help: "With this page you can import CSV Reviews files to then run an automated review for all text's pressing the 'Run' button"
                actions:
                    - { name: 'show', label: 'View', icon: 'eye' }
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'remove' }
                    - { name: 'new', icon: 'plus' }
                max_results: 50
                fields:
                    - { property: 'text', label: 'Text' }
                    - { property: 'my_review', label: 'Review', type: array }
                    - { property: 'my_score', label: 'Score', type: integer }
                sort: ['id', 'ASC']
            search:
                sort: ['id', 'ASC']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Textual review' }
                    - { property: 'text', label: 'Text', help: 'Textual review by customer...' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Dinamic review' }
                    - { property: 'myReview', label: 'Review', help: 'The review items...' }
                    - { type: 'section', label: 'The score...' }
                    - { property: 'myScore', label: 'Score', help: 'The review score...', type: integer }
        Scores:
            class: AppBundle\Entity\Scores
            help: "The 'Scores' are the values for the positive or negative apreciation criteria..."
            label: 'Scores'
            list:
                title: "Most recent Scores..."
                actions:
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'remove' }
                    - { name: 'new', icon: 'plus' }
                max_results: 50
                fields: 
                    - { property: 'value', label: 'Name'}
                    - { property: 'score', label: 'Score' } 
                sort: ['id', 'ASC']
            search:
                sort: ['id', 'ASC']
            form:
                fields:
                    - { property: 'value', label: 'Name', help: 'The score name...'}
                    - { property: 'score', label: 'Score', help: 'The score value...', type: integer } 
        Topics:
            class: AppBundle\Entity\Topics
            help: "The 'Topics' to consider during the reviews scan..."
            label: 'Topics'
            list:
                title: "Most recent Topics..."
                actions:
                    - { name: 'edit', icon: 'pencil' }
                    - { name: 'delete', icon: 'remove' }
                    - { name: 'new', icon: 'plus' }
                max_results: 50
                fields: 
                    - { property: 'value', label: 'Topic name' }
                sort: ['id', 'ASC']
            search:
                sort: ['id', 'ASC']      
            form:
                fields:
                    - { property: 'value', label: 'Topic', help: 'The topic name...' }

# assetic bundle configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~                    
