AppBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        email:
            type: string
            scale: 255
        phonenum:
            type: string
            scale: 255
        address:
            type: string
            scale: 255